fff:
  outputs:

    rds_target:
      dbname: postgres
      host: destination2.cxjxmknm7hv1.us-east-1.rds.amazonaws.com
      pass: suraj123
      port: 5432
      schema: postgres_rds_public
      threads: 1
      type: postgres
      user: postgres

  target: rds_target